###
//GET http://localhost:3000/users HTTP/1.1
//content-type: application/json

###
GET http://localhost:3000/users?age=14 HTTP/1.1
content-type: application/json

###
GET http://localhost:3000/user?cell=82999953339 HTTP/1.1
content-type: application/json

###
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "name":"Aliny",
    "cpf": "243423",
    "age": 12,
    "cell": 82999953339
}

###
PATCH http://localhost:3000/users/604967b48950f35ed853fc64 HTTP/1.1
content-type: application/json

{
    "name":"Carlos"
}

###
DELETE  http://localhost:3000/users/604967b48950f35ed853fc65 HTTP/1.1
content-type: application/json